theme = "dracula_at_night"

[editor]
auto-save = true
bufferline = "multiple"
color-modes = true
cursorline = true
rulers = [80, 120]
soft-wrap.enable = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
";" = "command_mode"

"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"

"A-x" = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.insert]
j = { k = "normal_mode" }
C-h = "delete_char_backward"
C-l = "move_char_right"
C-s = ["save_selection", ":w"]
