alias aus='shutdown now'
alias clip='xclip -selection clipboard'
alias dla='youtube-dl -x -f bestaudio --write-description --restrict-filenames --add-metadata --xattrs --write-sub --sub-lang en,en-GB,de'
alias dlv='youtube-dl -f bestvideo+bestaudio --write-description --restrict-filenames --add-metadata --xattrs --merge-output-format mkv --embed-subs --all-subs'
alias dlvl='youtube-dl -f worstvideo+worstaudio --write-description --restrict-filenames --add-metadata --xattrs --merge-output-format mkv --embed-subs --all-subs'
alias dlcv='youtube-dl --skip-download --continue --no-post-overwrites --no-overwrites --restrict-filenames --ignore-errors --output "%(playlist)s/subtitles/%(upload_date)s_%(playlist_index)s_%(title)s-%(id)s.%(ext)s" --write-sub --all-subs --batch-file urls --quiet > >(tee list_subs) && youtube-dl --continue --download-archive index --no-post-overwrites --no-overwrites --restrict-filenames --ignore-errors -f "worstvideo+worstaudio" --add-metadata --xattrs --output "%(playlist)s/%(upload_date)s_%(playlist_index)s_%(title)s-%(id)s.%(ext)s" --write-description --merge-output-format mkv --embed-subs --all-subs --batch-file urls --playlist-random --quiet > >(tee list)'
alias dlca='youtube-dl -x --continue --download-archive index --no-post-overwrites --no-overwrites --restrict-filenames --ignore-errors -f bestaudio --add-metadata --xattrs --output "%(playlist)s/%(upload_date)s_%(playlist_index)s_%(title)s-%(id)s.%(ext)s" --write-description --embed-subs --all-subs --batch-file urls --playlist-random | tee list'
alias dvd='mpv dvd://'
alias e='emacsclient'
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'
alias ll='ls -CFAlhv --color=auto --group-directories-first'
alias lll='tree -afpuhFi --dirsfirst -L 1 --'
alias log='loginctl kill-session $(loginctl list-sessions | head -n 2 | tail -n 1 | awk "{ print \$1 }")'
alias m='mpv --no-audio-display --shuffle $(cat playlist.m3u|shuf)'
alias mkdir='mkdir -pv'
alias mv='mv -v'
alias psk='ps -ely | grep'
alias r='ranger'
alias raus='lsblk -e7; udisksctl unmount --no-user-interaction --block-device'
alias rein='lsblk -e7; udisksctl mount --no-user-interaction --block-device'
alias rm='rm -rf'
alias rmdir='rmdir --ignore-fail-on-non-empty -v'
alias rp='rsync -vaHAX'
alias syncthing='syncthing -browser-only'
alias today='touch $(date -I)_'
alias update='sudo apt update && apt list --upgradable && sudo apt upgrade && sudo apt autoremove && sudo apt-get autoclean && flatpak update && flatpak uninstall --delete-data --unused && sudo youtube-dl --update'
alias v='vi'
alias workgit='pass -c ssh-keygen-github; ssh-add ~/.ssh/github'
alias wmpm='for url in $(find . -type f -name "urls"); do cd "$(dirname "$url")"; wmp; cd -; done'
alias xfix='export DISPLAY=:0 ; xrandr --output "DP-0" --off --output "HDMI-0" --primary --auto'
alias  fxi='export DISPLAY=:0 ; xrandr --output "DP-0" --off --output "HDMI-0" --primary --auto'
alias  xfi='export DISPLAY=:0 ; xrandr --output "DP-0" --off --output "HDMI-0" --primary --auto'
alias  xfx='export DISPLAY=:0 ; xrandr --output "DP-0" --off --output "HDMI-0" --primary --auto'
alias   fx='export DISPLAY=:0 ; xrandr --output "DP-0" --off --output "HDMI-0" --primary --auto'
alias   ix='export DISPLAY=:0 ; xrandr --output "DP-0" --off --output "HDMI-0" --primary --auto'
